services:
  backend:
    build:
      context: ./backend
    container_name: teamora-backend
    env_file:
      - ./backend/.env.production
    command: >
      sh -c "
        python manage.py migrate_schemas --shared &&
        gunicorn backend.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
      "
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    build:
      context: ./backend
    container_name: teamora-celery
    command: celery -A backend worker --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - backend
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.local

  celery-beat:
    build:
      context: ./backend
    container_name: teamora-celery-beat
    command: celery -A backend beat --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - backend
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.local

  db:
    image: postgres:17
    container_name: teamora-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: teamora
      POSTGRES_USER: teamora
      POSTGRES_PASSWORD: teamora
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: teamora-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: