services:
  backend:
    build:
      context: ./backend
    container_name: teamora-backend
    env_file:
      - ./backend/.env
    command: >
      sh -c "
        python manage.py migrate &&
        daphne -b 0.0.0.0 -p 8000 backend.asgi:application
      "
    volumes:
      - ./backend:/app
    expose: 
      - "8000"
    depends_on:
      - db
      - redis
    
  nginx:
    image: nginx:alpine
    container_name: teamora-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - backend

  celery:
    build:
      context: ./backend
    container_name: teamora-celery
    command: celery -A backend worker --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - backend
      - redis

  celery-beat:
    build:
      context: ./backend
    container_name: teamora-celery-beat
    command: celery -A backend beat --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - backend
      - redis

  db:
    image: postgres:17
    container_name: teamora-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: teamora-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: